goldStore/Areas/Panel/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldStore.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.productImage = new HashSet<productImage>();
        }
    
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> oldPrice { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> brandId { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productImage> productImage { get; set; }
    }
}

goldStore/Areas/Panel/Controllers/ProductController.cs
using goldStore.Areas.Panel.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace goldStore.Areas.Panel.Controllers
{
    public class ProductController : Controller
    {
        ProductRepository repository = new ProductRepository(new Models.goldstoreEntities());
        // GET: Panel/Product
        public ActionResult Index()
        {
            return View(repository.GetAll());
        }
        public ActionResult Create()
        {
            ViewBag.Categories = repository.GetCategories();
            ViewBag.Brands= repository.GetBrands();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(product product, IEnumerable<HttpPostedFileBase> image1)
        {
            if (product != null)
            {
                repository.Save(product);
            }
          if (image1.First() != null)
            {
                productImage newImg = new productImage();
                newImg.productId = product.productId;

                foreach (var item in image1)
                {
                    using (var br = new BinaryReader(item.InputStream))
                    {
                        var data = br.ReadBytes(item.ContentLength);
                        newImg.image = data;
                    }
                    repository.Save(newImg);
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var selectedBrand = repository.Get(id).brandId;
            var selectedCategory = repository.Get(id).categoryId;

          ViewBag.Categories = new SelectList(repository.GetCategories(),"categoryId","categoryName",selectedCategory);
          ViewBag.Brands = new SelectList(repository.GetBrands(),"brandId","brandName",selectedBrand);
          return View(repository.Get(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(product product,IEnumerable<HttpPostedFileBase> image1)
        {
            if(product!=null)
            {
                repository.Update(product);
            }
            if (image1.First() != null)
            {
                productImage newImg = new productImage();
                newImg.productId = product.productId;

                foreach (var item in image1)
                {
                    using (var br = new BinaryReader(item.InputStream))
                    {
                        var data = br.ReadBytes(item.ContentLength);
                        newImg.image = data;
                    }
                    repository.Save(newImg);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
       public void deleteImage(int imageId)
        {
            repository.Delete(imageId);
        }
    }
}

goldStore/Controllers/ShopController.cs
using goldStore.Areas.Panel.Controllers;
using goldStore.Areas.Panel.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace goldStore.Controllers
{
    public class ShopController : Controller
    {
        ProductRepository repoProduct = new ProductRepository(new Areas.Panel.Models.goldstoreEntities());
        CategoryRepository repoCategory = new CategoryRepository(new Areas.Panel.Models.goldstoreEntities());
        // GET: Shop
        public ActionResult Index()
        {
            return RedirectToAction("Products");
        }
        public PartialViewResult PartialCategory()
        {
        return PartialView(repoCategory.GetAll());
        }
        public ActionResult Products(int?categoryId)
        {
            var result = repoProduct.GetAll();
            if (categoryId!=null)
            {
                result = result.Where(x => x.categoryId == categoryId).ToList();
            }
            return View(result);
        }
        
    }
}

goldStore/Views/Shop/PartialCategory.cshtml
@model IEnumerable<goldStore.Areas.Panel.Models.category>
<ul class="ht__cat__list">
   @foreach(var item in Model)
   {
       <li><a href="@Url.Action("Products","Shop",new { categoryId = item.categoryId })">@item.categoryName</a></li>
   }
    
</ul>

goldStore/Views/Shop/Products.cshtml
@model IEnumerable<goldStore.Areas.Panel.Models.product>
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/_Shared/_LayoutShop.cshtml";
}

<div class="col-lg-9 col-lg-push-3 col-md-9 col-md-push-3 col-sm-12 col-xs-12">
    <div class="htc__product__rightidebar">
        <div class="htc__grid__top">
            <div class="htc__select__option">
               
            </div>
            <div class="ht__pro__qun">
                <span>Showing 1-12 of 1033 products</span>
            </div>
            <!-- Start List And Grid View -->
            <ul class="view__mode" role="tablist">
                <li role="presentation" class="grid-view active"><a href="#grid-view" role="tab" data-toggle="tab"><i class="zmdi zmdi-grid"></i></a></li>
                <li role="presentation" class="list-view"><a href="#list-view" role="tab" data-toggle="tab"><i class="zmdi zmdi-view-list"></i></a></li>
            </ul>
            <!-- End List And Grid View -->
        </div>
        <!-- Start Product View -->
        <div class="row">
            <div class="shop__grid__view__wrap">
                <div role="tabpanel" id="grid-view" class="single-grid-view tab-pane fade in active clearfix">
                    <!-- Start Single Product -->
                   
                    @foreach (var product in Model)
                    {
                        //Gridd görünüm

                        <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
                            <div class="category">
                                <div class="ht__cat__thumb">
                                    <a href="product-details.html">
                                        <img src="data:image/png;base64,@Convert.ToBase64String(@product.productImage.FirstOrDefault().image)" alt="product images">
                                    </a>
                                </div>
                                <div class="fr__hover__info">
                                    <ul class="product__action">
                                        <li><a href="@Url.Action("WishList","Account")"><i class="icon-heart icons"></i></a></li>

                                        <li><a href="@Url.Action("Basket","Shop")"><i class="icon-handbag icons"></i></a></li>

                                        <li><a href="@Url.Action("Compare","Shop")"><i class="icon-shuffle icons"></i></a></li>
                                    </ul>
                                </div>
                                <div class="fr__product__inner">
                                    <h4><a href="product-details.html">@product.productName</a></h4>
                                    <ul class="fr__pro__prize">
                                        <li class="old__prize">₺@product.oldPrice</li>
                                        <li>₺@product.price</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                       
                    }

                </div>
                <div role="tabpanel" id="list-view" class="single-grid-view tab-pane fade clearfix">
                    <div class="col-xs-12">
                        <div class="ht__list__wrap">
                           
                            @foreach (var product in Model)
                            {
                                <!-- Start List Product -->
                                <div class="ht__list__product">
                                    <div class="ht__list__thumb">
                                        <a href="@Url.Action("ProductDetail","Shop",new { productId = product.productId })" ><img src="data:image/png;base64,@Convert.ToBase64String(@product.productImage.FirstOrDefault().image)" alt="product images"></a>
                                    </div>
                                    <div class="htc__list__details">
                                        <h2><a href="@Url.Action("ProductDetail","Shop",new{ productId = product.productId })">@product.productName</a></h2>
                                        <ul class="pro__prize">
                                            <li class="old__prize">₺ @product.oldPrice</li>
                                            <li>₺@product.price</li>
                                        </ul>
                                        <ul class="rating">
                                            <li><i class="icon-star icons"></i></li>
                                            <li><i class="icon-star icons"></i></li>
                                            <li><i class="icon-star icons"></i></li>
                                            <li class="old"><i class="icon-star icons"></i></li>
                                            <li class="old"><i class="icon-star icons"></i></li>
                                        </ul>
                                        <p>@product.description</p>
                                        <div class="fr__list__btn">
                                            <a class="fr__btn" href="cart.html">Sepete Ekle</a>
                                        </div>
                                    </div>
                                </div>

                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Product View -->
    </div>
    <!-- Start Pagenation -->
    <div class="row">
        <div class="col-xs-12">
            <ul class="htc__pagenation">
                <li><a href="#"><i class="zmdi zmdi-chevron-left"></i></a></li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">3</a></li>
                <li><a href="#">19</a></li>
                <li><a href="#"><i class="zmdi zmdi-chevron-right"></i></a></li>
            </ul>
        </div>
    </div>
    <!-- End Pagenation -->
</div>